### ISSUE TITLE
RRF limited to 1000 docs?

### ISSUE THREAD

**Issue by lintool** [joaopalotti/trectools#22]
RRF allows user to specify `max_docs`:
https://github.com/joaopalotti/trectools/blob/9e76486385fcab77f993650f079d7a3db91c3328/trectools/fusion.py#L106

However, it seems only up to 1000 hits:
https://github.com/joaopalotti/trectools/blob/9e76486385fcab77f993650f079d7a3db91c3328/trectools/fusion.py#L123

Shouldn't `max_docs` be passed into _n_?

**Comment by x65han** [comment]
I got this

**Comment by joaopalotti** [comment]
Thanks, Jimmy for reporting it!
Johnson Han, thanks for taking care of it. I really appreciate it! 
Looking forward to receiving your pull request.

**Comment by joaopalotti** [comment]
I had a look at this issue and we do not necessarily want to have:
` docs_for_run = r.get_top_documents(topic, n=max_docs) `

The parameter `max_docs` is only used for the final list of documents after the merging. Another parameter could be created to filter the top X documents of each run, if this is a use case.

Closing this issue for now.
