### ISSUE TITLE
Querying IR Systems

### ISSUE THREAD

**Issue by amallia** [joaopalotti/trectools#4]
Would you accept a PR if I integrate [PISA](https://github.com/pisa-engine/pisa) as an IR system?

**Comment by joaopalotti** [comment]
Absolutely!

**Comment by amallia** [comment]
Working on this, hopefully it will be ready before your demo.

I am wondering if this tool assumes that the index has been already created...

**Comment by joaopalotti** [comment]
It would be great if this is ready before the demo. By the way, is there are paper from PISA toolkit that we can refer?

The tool assumes that the index has been already created in a previous step, but extensions to create a (PISA/Terrier/Indri/etc) index using all documents from a folder are welcome.

**Comment by amallia** [comment]
> It would be great if this is ready before the demo. By the way, is there are paper from PISA toolkit that we can refer?
We don't have a paper on `PISA` yet

**Comment by amallia** [comment]
Created PR: https://github.com/joaopalotti/trectools/pull/9
